import HomeNavigation from "@/components/home/homeNavigation";
import PersonCard from "@/components/home/personCard";
import Post from "@/components/home/post";
import UserStatusInput from "@/components/home/userStatusInput";
import LeftSide from "@/components/leftSide";
import RightSide from "@/components/rightSide";
import { posts } from "@/dummyData/posts.json";
import { recommendedFriends } from "@/dummyData/recommendedFriends.json";
import appPages from "@/shared/appPages";
import { ArrowForwardRounded } from "@material-ui/icons";
import { signIn, useSession } from "next-auth/react";
import Head from "next/head";
import Image from "next/image";
import { useEffect } from "react";
import styles from "./styles.module.css";

export default function Home() {
  const { data: session } = useSession();

  useEffect(() => {
    if ((session as any)?.error === "RefreshAccessTokenError") {
      signIn(); // Force sign in to hopefully resolve error
    }
  }, [session]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <LeftSide currentPage={appPages.home} />
        <div className={styles.contentContainer}>
          <HomeNavigation />
          <UserStatusInput />
          <div className={styles.recommendedPeople}>
            <div className={styles.cardListHeader}>
              <p>Follow People</p>
              <ArrowForwardRounded style={{ cursor: "pointer" }} />
            </div>
            <div className={styles.recommendList}>
              {recommendedFriends.map((person) => {
                return <PersonCard key={person.id} {...person} />;
              })}
            </div>
          </div>
          <div className={styles.listPost}>
            {posts.map((post) => (
              <Post key={post.id} {...post} />
            ))}
          </div>
        </div>
        <RightSide />
      </main>
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
